meta_product_name: "FLASH"
meta_title: "FLASH - GET DECKED OUT!"
meta_description: "Flashcards are an incredibly versatile study tool. While many students think of using them for simple facts, they can be used for complex processes throughout one's academic career."
meta_image: "flash-better.png" # should exist in `app/assets/images/`
